Edit_DD_lst = ['Date','Population','Load Slip #','Sample Load','TM9 Ticket','Owner',
    'Hauling Contractor','Working Circle','Block #','Logging Co.','Truck License Plate #',
    'Truck #','Truck Axle','Gross Weight','Tare Weight','Net Weight','Disposition/FMA #']

DB_list = ['daterecieved', 'poploadslip',
                    'count',
                    'sampleloads' ,
                    'tm9_ticket',
                    'owner' ,
                    'disposition_fmanum' ,
                    'workingcircle' ,
                    'blocknum',
                    'loggingco' ,
                    'haulingcontractor',
                    'truckplate',
                    'trucknum' ,
                    'truckaxle' ,
                    'grossweight',
                    'timeIn',
                    'tareweight',
                    'netweight',
                    'timeOut' ]

Update_Scaler = {'numpcsreceived': self.numPcs_enter,
  'logsreject' : self.rejects_enter,
  'totalvol' : self.TotalVol_enter,
  'avgpc' : self.AvgpcBark_enter,
  'conversion': self.Conversion_enter ,
  'totalvolsaw': self.TotV_enter ,
  'avgpcsaw' : self.AvgpcSaw_enter ,
  'returnssaw': self.returns_enter ,
  'polemat': self.poleMat_enter }
